module.exports = {
	appName: "VMeet DB",
	// baseUrl: "http://localhost:9103/vmeet-db",
	baseUrl: "https://modoto.net/vmeet-db",
	url: "/vmeet-db",
	port: 9103,
	encodedLimit: "50mb",
	http: true,
	// googleRedirectApi: "http://localhost:9103/vmeet-db/api/google/auth",
	// videoConferenceUrl: "https://localhost:9102/vmeet",
	googleRedirectApi: "https://modoto.net/vmeet-db/api/google/auth",
	videoConferenceUrl: "https://modoto.net/vmeet",
	// googleRedirectApi: "http://localhost:9101/api/google/auth",
	// videoConferenceUrl: "https://localhost:9100/telepati",
	googleOauthUrl: "https://www.googleapis.com/oauth2/v2",
	// googleRedirectApi: "https://localhost:9100/telepati",
	googleScope: ["https://www.googleapis.com/auth/calendar", "openid", "email", "profile"],
}
